
# right word replaces left work
res = {'rare liquid': 'rareliquid',
       'allright': 'Alright',
       'all right': 'Alright',
       'i ': 'I ',
       'ben ': 'Ben ',
       "i'll ": "I'll ",
       "i'm ": "I'm ",
       "i've ": "I've ",
       ' um': '',
       ' uh': '',
       'elon': 'Elon',
       'musk': 'Musk',
       'tesla': 'Tesla',
       'oprah': 'Oprah',
       'solana': 'Solana',
       'ebit': 'EBIT',
       'wacc': 'WACC',
       'ebitda': 'EBITA',
       'dcf': 'DCF',
       'tps': 'TPS',
       "january": "January",
       "febuary": "Febuary",
       "march": "March",
       "april": "April",
       "june": "June",
       "july": "July",
       "august": "August",
       "september": "September",
       "october": "October",
       "november": "November",
       "december": "December",
       "jp": "J.P.",
       "morgan": "Morgan",
       "jp morgan": "J.P. Morgan",
       "J.P.Morgan": "J.P. Morgan",
       "mba": "MBA",
       "gpa": "GPA",
       "europe": "Europe",
       "asia": "Asia",
       "america": "America",
       "australia": "Australia",
       "berkeley": "Berkeley",
       "uc Berkeley": "UC Berkeley",
       "J.P.m": "JPM"}

checkWords = list(res.keys())
repWords = list(res.values())
(checkWords,repWords) = zip(*res.items())
